-- vim.api.nvim_create_autocmd("PackChanged", {G
--     callback = function(ev)
--         local name, kind = ev.data.spec.name, ev.data.kind
--         if name == "nvim-treesitter" and kind == "update" then
--             if not ev.data.active then
--                 vim.cmd.packadd "nvim-treesitter"
--             end
--             vim.cmd "TSUpdate"
--         end
--     end,
-- })
--
-- vim.pack.add {
--     { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
-- }
--
-- require("nvim-treesitter").install {
--     "bash",
--     "c",
--     "css",
--     "dockerfile",
--     "go",
--     "html",
--     "javascript",
--     "json",
--     "jsx",
--     "just",
--     "regex",
--     "typescript",
--     "tsx",
--     "lua",
--     "luadoc",
--     "markdown",
--     "markdown_inline",
--     "python",
--     "rust",
--     "terraform",
--     "toml",
--     "xml",
--     "yaml",
-- }
--
-- -- Enable treesitter highlighting automatically for all supported filetypes
-- vim.api.nvim_create_autocmd("FileType", {
--     callback = function(args)
--         local lang = vim.treesitter.language.get_lang(vim.bo[args.buf].filetype)
--         if lang then
--             pcall(vim.treesitter.start, args.buf, lang)
--         end
--     end,
-- })
